name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Actions Repository
          uses: actions/checkout@v3

        - name: Run PSSA
          uses: devblackops/github-action-psscriptanalyzer@master
          with:
            failOnErrors: true
            failOnWarnings: true
            failOnInfos: true
